spring:
  datasource:
    url: jdbc:mysql://localhost:3307/reservas_dev
    username: root
    password: root

mensaje:
  ambiente: "DESARROLLO"
  descripcion: "Configuración con base de datos en Docker"
